# Prometheus 配置文件
global:
  scrape_interval: 15s # 全局抓取间隔
  evaluation_interval: 15s # 规则评估间隔
  external_labels:
    monitor: 'gpu-monitoring'

# 告警规则文件
rule_files:
  - "rules/*.yml"

# 抓取配置
scrape_configs:
  # Prometheus 自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # DCGM Exporter - GPU 指标
  - job_name: 'dcgm-exporter'
    static_configs:
      - targets: ['dcgm-exporter:9400']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Node Exporter - 系统指标
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # cAdvisor - 容器指标
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s

  # 如果你有其他 GPU 监控目标，可以添加在这里
  # 例如：海光卡 exporter
  # - job_name: 'hygon-gpu-exporter'
  #   static_configs:
  #     - targets: ['hygon-exporter:9401']
  #   scrape_interval: 10s

# 告警管理器配置 (可选)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093
