# Prometheus配置文件 - 海光DCU监控
# 配置Prometheus抓取海光DCU指标

global:
  scrape_interval: 15s          # 全局抓取间隔
  evaluation_interval: 15s      # 规则评估间隔
  external_labels:
    cluster: 'hygon-dcu-cluster'
    environment: 'production'

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# 规则文件
rule_files:
  - "rules/*.yml"

# 抓取配置
scrape_configs:
  # 海光DCU Exporter
  - job_name: 'hygon-dcu-exporter'
    static_configs:
      - targets: 
          - '192.7.111.66:9400'  # 服务器1
          - '192.7.111.67:9400'  # 服务器2  
          - '192.7.111.68:9400'  # 服务器3
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics
    params:
      format: ['prometheus']
    relabel_configs:
      # 添加服务器标签
      - source_labels: [__address__]
        target_label: server
        regex: '([^:]+):.*'
        replacement: '${1}'
      # 添加实例标签
      - source_labels: [__address__]
        target_label: instance
        replacement: '${1}'

  # Prometheus自监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: /metrics

  # Node Exporter (系统指标)
  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - '192.7.111.66:9100'
          - '192.7.111.67:9100'
          - '192.7.111.68:9100'
    scrape_interval: 30s
    metrics_path: /metrics

  # Grafana监控
  - job_name: 'grafana'
    static_configs:
      - targets: ['192.7.111.66:3000']
    scrape_interval: 30s
    metrics_path: /metrics

# 存储配置
storage:
  tsdb:
    path: /var/lib/prometheus/
    retention.time: 30d          # 数据保留30天
    retention.size: 50GB         # 最大存储50GB
    wal-compression: true        # 启用WAL压缩

# 远程写入配置 (可选)
# remote_write:
#   - url: "http://remote-storage:9201/write"
#     queue_config:
#       max_samples_per_send: 1000
#       max_shards: 200
#       capacity: 2500

# 远程读取配置 (可选)  
# remote_read:
#   - url: "http://remote-storage:9201/read"
