# GPU 监控告警规则
groups:
  - name: gpu-alerts
    rules:
      # GPU 温度过高告警
      - alert: GPUHighTemperature
        expr: DCGM_FI_DEV_GPU_TEMP > 80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "GPU 温度过高"
          description: "GPU {{ $labels.gpu }} 温度为 {{ $value }}°C，超过阈值 80°C"

      # GPU 利用率过高告警
      - alert: GPUHighUtilization
        expr: DCGM_FI_DEV_GPU_UTIL > 95
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "GPU 利用率过高"
          description: "GPU {{ $labels.gpu }} 利用率为 {{ $value }}%，持续超过 95%"

      # GPU 功耗过高告警
      - alert: GPUHighPowerUsage
        expr: DCGM_FI_DEV_POWER_USAGE > 300
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "GPU 功耗过高"
          description: "GPU {{ $labels.gpu }} 功耗为 {{ $value }}W，超过阈值 300W"

      # GPU XID 错误告警
      - alert: GPUXIDError
        expr: increase(DCGM_FI_DEV_XID_ERRORS[5m]) > 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "GPU XID 错误"
          description: "GPU {{ $labels.gpu }} 出现 XID 错误，错误码: {{ $value }}"

      # GPU 显存使用率过高告警
      - alert: GPUHighMemoryUsage
        expr: (DCGM_FI_DEV_FB_USED / (DCGM_FI_DEV_FB_USED + DCGM_FI_DEV_FB_FREE)) * 100 > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "GPU 显存使用率过高"
          description: "GPU {{ $labels.gpu }} 显存使用率超过 90%"

      # DCGM Exporter 服务不可用
      - alert: DCGMExporterDown
        expr: up{job="dcgm-exporter"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "DCGM Exporter 服务不可用"
          description: "DCGM Exporter 服务已停止响应"
